"""add workflow timestamps.

Revision ID: 465d6f3db028
Revises: b2783184ce1a
Create Date: 2026-06-26 10:38:45.582533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "465d6f3db028"
down_revision: str | Sequence[str] | None = "b2783184ce1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow", sa.Column("created", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE workflow SET created = NOW() WHERE created IS NULL")
    op.alter_column("workflow", "created", nullable=False)
    op.add_column(
        "workflow", sa.Column("start_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "workflow", sa.Column("end_time", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "end_time")
    op.drop_column("workflow", "start_time")
    op.drop_column("workflow", "created")
    # ### end Alembic commands ###
