"""Initial schema.

Revision ID: b2783184ce1a
Revises:
Create Date: 2026-06-15 11:06:21.839663

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2783184ce1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("workflow_type", sqlmodel.AutoString(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PROCESSING", "SUCCESS", "ERROR", name="workflowstatus"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow")
    sa.Enum(name="workflowstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
